[package]
name = "agama-cli"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.19", features = ["derive", "wrap_help"] }
curl = { version = "0.4.47", features = ["protocol-ftp"] }
agama-lib = { path="../agama-lib" }
serde_json = "1.0.128"
indicatif= "0.17.8"
thiserror = "1.0.64"
console = "0.15.8"
anyhow = "1.0.89"
tempfile = "3.13.0"
nix = { version = "0.27.1", features = ["user"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
async-trait = "0.1.83"
reqwest = { version = "0.11", features = ["json"] }
url = "2.5.2"
inquire = { version = "0.7.5", default-features = false, features = ["crossterm", "one-liners"] }
chrono = "0.4.38"

[[bin]]
name = "agama"
path = "src/main.rs"
