[workspace]
members = [
    "agama-autoinstall",
    "agama-cli",
    "agama-server",
    "agama-lib",
    "agama-locale-data",
    "agama-network",
    "agama-utils",
    "xtask",
]
resolver = "2"

[workspace.package]
# required by zbus 5
rust-version = "1.81"
edition = "2021"
