[workspace]
members = [
  "agama-cli",
  "agama-server",
  "agama-derive",
  "agama-lib",
  "agama-locale-data",
  "agama-settings",
]
resolver = "2"

[workspace.package]
rust-version = "1.74"
edition = "2021"
