[package]
name = "agama-autoinstall"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
agama-lib = { path = "../agama-lib" }
agama-utils = { path = "../agama-utils" }
agama-transfer = { path = "../agama-transfer" }
anyhow = { version = "1.0.98" }
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = "1.46.0"
url = "2.5.4"
agama-l10n = { path = "../agama-l10n" }
