[package]
name = "zypp-agama"
version = "0.1.0"
edition = "2021"

[dependencies]
zypp-agama-sys = { path="./zypp-agama-sys" }
url = "2.5.7"
tracing = "0.1.41"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
glob = "0.3.1"

[[bench]]
name = "list_patterns"
harness = false
