name: Submit agama-live

on:
  # runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      # run only when a live ISO source is changed
      - live/**

jobs:
  update_staging_package:
    # do not run in forks which do not set the OBS_PROJECT variable
    if: vars.OBS_PROJECT != ''

    runs-on: ubuntu-latest

    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Configure and refresh repositories
        # disable unused repositories to have a faster refresh
        run: zypper modifyrepo -d repo-non-oss repo-openh264 repo-update && zypper ref

      - name: Install tools
        run: zypper --non-interactive install --no-recommends
             make osc

      - name: Configure osc
        run: .github/workflows/configure_osc.sh
        env:
          OBS_USER:     ${{ secrets.OBS_USER }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}

      - name: Checkout ${{ vars.OBS_PROJECT }} agama-live
        run: osc co -o dist ${{ vars.OBS_PROJECT }} agama-live
        working-directory: ./live

      - name: Build sources
        run: make clean && make
        working-directory: ./live

      - name: Update OBS files
        run: osc addremove
        working-directory: ./live/dist

      - name: Check status
        run: osc diff && osc status
        working-directory: ./live/dist

      - name: Commit agama-live to ${{ vars.OBS_PROJECT }}
        run:  osc commit -m "Updated to Agama $GITHUB_SHA"
        working-directory: ./live/dist
